---

# Ensure facts for localhost are gathered
- setup: {}
  become: true
  become_user: root
  delegate_facts: true
  register: my_facts

- block:

  - name: vagrant check version
    shell: vagrant --version | grep -o -E '[0-9.]*'
    failed_when: no
    ignore_errors: yes
    check_mode: no
    register: vagrant_version

  # install vagrant (base xenial version is too old)
  - name: vagrant install (== 1.95)
    apt:
      deb: "{{ _vagrant_deb_url }}"
    when: vagrant_version.rc != 0 or vagrant_version.stdout | trim | version_compare('1.8.5', '<')

  # check virtualbox repository
  - name: virtualbox repository keys
    apt_key: id={{ item }} keyserver=keys.gnupg.net
    with_items:
      - 7B0FAB3A13B907435925D9C954422A4B98AB5139
      - B9F8D658297AF3EFC18D5CDFA2F683C52980AECF

  - name: virtualbox repository
    apt_repository:
      repo: deb http://download.virtualbox.org/virtualbox/debian {{ my_facts['ansible_facts']['ansible_lsb']['id'] }} non-free contrib
      state: present
      filename: virtualbox

  - name: dkms installation
    package: name=dkms state=present

  - name: dkms installation
    package: name=virtualbox-{{ _vagrant_virtualbox_deb_version }} state=present

  # warning: we are on a delegated task, so we need to lookup
  # ansible_distribution on delegated host
  when: my_facts['ansible_facts']['ansible_lsb']['id'] == 'Ubuntu'
  become: yes
  become_user: root
